In [188]:
import pandas as pd

In [189]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
#https://www.kaggle.com/blastchar/telco-customer-churn

In [190]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [191]:
df.shape

(7043, 21)

In [192]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [193]:
df['StreamingMovies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [194]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [195]:
df.dropna(inplace = True)

In [196]:
class onehotencoder:    
    
    def __init__(self, dataframe,encodingvalue):
        self.encode(dataframe,encodingvalue)
        
    def coloumnencoder(self ,i , encodingvalue):
    #encodingvalue =  [('Yes' , 1), ('No' , 0)]
        retundata = 9
        for k,v in encodingvalue:   
            if(i == k):
                retundata =  v
        return retundata;
    
    def encode(self,dataframe, encodingvalue):  
        index = 0
        for i in dataframe:    
            #print(i,self.coloumnencoder(i),index)
            dataframe[index] = self.coloumnencoder(i ,encodingvalue )
            index +=1

In [197]:
def preparedictionary(datafram ,coloumnname):
    dicdata = []
    index = 0
    for i in datafram[coloumnname].unique():
        dicdata.append((i,index))
        index +=1
    print("coloumnname ::" , coloumnname , dicdata)
    return dicdata

In [198]:
coltobeencoded = ['gender', 'Partner', 'Dependents','PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport','StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod','Churn' ]

for i in coltobeencoded:
    dictdata = preparedictionary(df,i)
    onehotencoder(df[i][:],dictdata)

coloumnname :: gender [('Female', 0), ('Male', 1)]
coloumnname :: Partner [('Yes', 0), ('No', 1)]
coloumnname :: Dependents [('No', 0), ('Yes', 1)]
coloumnname :: PhoneService [('No', 0), ('Yes', 1)]
coloumnname :: MultipleLines [('No phone service', 0), ('No', 1), ('Yes', 2)]
coloumnname :: InternetService [('DSL', 0), ('Fiber optic', 1), ('No', 2)]
coloumnname :: OnlineSecurity [('No', 0), ('Yes', 1), ('No internet service', 2)]
coloumnname :: OnlineBackup [('Yes', 0), ('No', 1), ('No internet service', 2)]
coloumnname :: DeviceProtection [('No', 0), ('Yes', 1), ('No internet service', 2)]
coloumnname :: TechSupport [('No', 0), ('Yes', 1), ('No internet service', 2)]
coloumnname :: StreamingTV [('No', 0), ('Yes', 1), ('No internet service', 2)]
coloumnname :: StreamingMovies [('No', 0), ('Yes', 1), ('No internet service', 2)]
coloumnname :: Contract [('Month-to-month', 0), ('One year', 1), ('Two year', 2)]
coloumnname :: PaperlessBilling [('Yes', 0), ('No', 1)]
coloumnname :: PaymentMethod [('Electronic check', 0), ('Mailed check', 1), ('Bank transfer (automatic)', 2), ('Credit card (automatic)', 3)]
coloumnname :: Churn [('No', 0), ('Yes', 1)]

In [200]:
df.shape

(7043, 21)

In [202]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,29.85,29.85,0
1,5575-GNVDE,1,0,1,0,34,1,1,0,1,...,1,0,0,0,1,1,1,56.95,1889.5,0
2,3668-QPYBK,1,0,1,0,2,1,1,0,1,...,0,0,0,0,0,0,1,53.85,108.15,1
3,7795-CFOCW,1,0,1,0,45,0,0,0,1,...,1,1,0,0,1,1,2,42.30,1840.75,0
4,9237-HQITU,0,0,1,0,2,1,1,1,0,...,0,0,0,0,0,0,0,70.70,151.65,1

In [203]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [206]:
df.to_csv('pre-processesed churn.csv',index=False)